name = "Minecraft New Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecf6c0809ba0d1747c16c047942e32691fef68936cf4445c40ffa36d45556e93"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
