name = "Minecraft New Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a3f683aa1918b73138748f39686c77cbf6ec81cadb7cc5a90c78ce815ee7536"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
