name = "skyblock"
author = "Jorge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0484452b2f43e1fdd49cc96127f7c2fbbb3c849877c791112082568f38c41619"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.20", "1.20.0", "1.20.1"]
