name = "Minecraft New Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a9eaa0dcfb7acec5410be15fa5c32c199bbf62016a68fe55a2f3ef49b1f74ee"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
