name = "skyblock"
author = "Jorge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c49eeddbf263fab3377ea65d529fcb056776adbdc9e5ba60c2502713143da5"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.20", "1.20.0", "1.20.1"]
