name = "Minecraft New Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad6d94aec339ae87b7f119ce2a4673ee863e40de389ff7da66359c302afda2c4"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
